# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import classifier_pb2 as classifier__pb2


class SemanticClassifierServiceStub(object):
    """语义分类服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Classify = channel.unary_unary(
                '/semantic_router.SemanticClassifierService/Classify',
                request_serializer=classifier__pb2.ClassificationRequest.SerializeToString,
                response_deserializer=classifier__pb2.ClassificationResponse.FromString,
                )
        self.BatchClassify = channel.unary_unary(
                '/semantic_router.SemanticClassifierService/BatchClassify',
                request_serializer=classifier__pb2.BatchClassificationRequest.SerializeToString,
                response_deserializer=classifier__pb2.BatchClassificationResponse.FromString,
                )
        self.StreamClassify = channel.stream_stream(
                '/semantic_router.SemanticClassifierService/StreamClassify',
                request_serializer=classifier__pb2.ClassificationRequest.SerializeToString,
                response_deserializer=classifier__pb2.ClassificationResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/semantic_router.SemanticClassifierService/HealthCheck',
                request_serializer=classifier__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=classifier__pb2.HealthCheckResponse.FromString,
                )


class SemanticClassifierServiceServicer(object):
    """语义分类服务定义
    """

    def Classify(self, request, context):
        """单个文本分类
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchClassify(self, request, context):
        """批量文本分类
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamClassify(self, request_iterator, context):
        """流式分类（用于实时处理）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SemanticClassifierServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Classify': grpc.unary_unary_rpc_method_handler(
                    servicer.Classify,
                    request_deserializer=classifier__pb2.ClassificationRequest.FromString,
                    response_serializer=classifier__pb2.ClassificationResponse.SerializeToString,
            ),
            'BatchClassify': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchClassify,
                    request_deserializer=classifier__pb2.BatchClassificationRequest.FromString,
                    response_serializer=classifier__pb2.BatchClassificationResponse.SerializeToString,
            ),
            'StreamClassify': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamClassify,
                    request_deserializer=classifier__pb2.ClassificationRequest.FromString,
                    response_serializer=classifier__pb2.ClassificationResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=classifier__pb2.HealthCheckRequest.FromString,
                    response_serializer=classifier__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'semantic_router.SemanticClassifierService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SemanticClassifierService(object):
    """语义分类服务定义
    """

    @staticmethod
    def Classify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/semantic_router.SemanticClassifierService/Classify',
            classifier__pb2.ClassificationRequest.SerializeToString,
            classifier__pb2.ClassificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchClassify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/semantic_router.SemanticClassifierService/BatchClassify',
            classifier__pb2.BatchClassificationRequest.SerializeToString,
            classifier__pb2.BatchClassificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamClassify(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/semantic_router.SemanticClassifierService/StreamClassify',
            classifier__pb2.ClassificationRequest.SerializeToString,
            classifier__pb2.ClassificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/semantic_router.SemanticClassifierService/HealthCheck',
            classifier__pb2.HealthCheckRequest.SerializeToString,
            classifier__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
