// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.0
// source: classifier.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SemanticClassifierService_Classify_FullMethodName       = "/semantic_router.SemanticClassifierService/Classify"
	SemanticClassifierService_BatchClassify_FullMethodName  = "/semantic_router.SemanticClassifierService/BatchClassify"
	SemanticClassifierService_StreamClassify_FullMethodName = "/semantic_router.SemanticClassifierService/StreamClassify"
	SemanticClassifierService_HealthCheck_FullMethodName    = "/semantic_router.SemanticClassifierService/HealthCheck"
)

// SemanticClassifierServiceClient is the client API for SemanticClassifierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SemanticClassifierServiceClient interface {
	Classify(ctx context.Context, in *ClassificationRequest, opts ...grpc.CallOption) (*ClassificationResponse, error)
	BatchClassify(ctx context.Context, in *BatchClassificationRequest, opts ...grpc.CallOption) (*BatchClassificationResponse, error)
	StreamClassify(ctx context.Context, opts ...grpc.CallOption) (SemanticClassifierService_StreamClassifyClient, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type semanticClassifierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSemanticClassifierServiceClient(cc grpc.ClientConnInterface) SemanticClassifierServiceClient {
	return &semanticClassifierServiceClient{cc}
}

func (c *semanticClassifierServiceClient) Classify(ctx context.Context, in *ClassificationRequest, opts ...grpc.CallOption) (*ClassificationResponse, error) {
	out := new(ClassificationResponse)
	err := c.cc.Invoke(ctx, SemanticClassifierService_Classify_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticClassifierServiceClient) BatchClassify(ctx context.Context, in *BatchClassificationRequest, opts ...grpc.CallOption) (*BatchClassificationResponse, error) {
	out := new(BatchClassificationResponse)
	err := c.cc.Invoke(ctx, SemanticClassifierService_BatchClassify_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticClassifierServiceClient) StreamClassify(ctx context.Context, opts ...grpc.CallOption) (SemanticClassifierService_StreamClassifyClient, error) {
	stream, err := c.cc.NewStream(ctx, &SemanticClassifierService_ServiceDesc.Streams[0], SemanticClassifierService_StreamClassify_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &semanticClassifierServiceStreamClassifyClient{stream}
	return x, nil
}

type SemanticClassifierService_StreamClassifyClient interface {
	Send(*ClassificationRequest) error
	Recv() (*ClassificationResponse, error)
	grpc.ClientStream
}

type semanticClassifierServiceStreamClassifyClient struct {
	grpc.ClientStream
}

func (x *semanticClassifierServiceStreamClassifyClient) Send(m *ClassificationRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *semanticClassifierServiceStreamClassifyClient) Recv() (*ClassificationResponse, error) {
	m := new(ClassificationResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *semanticClassifierServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, SemanticClassifierService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SemanticClassifierServiceServer is the server API for SemanticClassifierService service.
// All implementations must embed UnimplementedSemanticClassifierServiceServer
// for forward compatibility
type SemanticClassifierServiceServer interface {
	Classify(context.Context, *ClassificationRequest) (*ClassificationResponse, error)
	BatchClassify(context.Context, *BatchClassificationRequest) (*BatchClassificationResponse, error)
	StreamClassify(SemanticClassifierService_StreamClassifyServer) error
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedSemanticClassifierServiceServer()
}

// UnimplementedSemanticClassifierServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSemanticClassifierServiceServer struct {
}

func (UnimplementedSemanticClassifierServiceServer) Classify(context.Context, *ClassificationRequest) (*ClassificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Classify not implemented")
}
func (UnimplementedSemanticClassifierServiceServer) BatchClassify(context.Context, *BatchClassificationRequest) (*BatchClassificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchClassify not implemented")
}
func (UnimplementedSemanticClassifierServiceServer) StreamClassify(SemanticClassifierService_StreamClassifyServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamClassify not implemented")
}
func (UnimplementedSemanticClassifierServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedSemanticClassifierServiceServer) mustEmbedUnimplementedSemanticClassifierServiceServer() {
}

// UnsafeSemanticClassifierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SemanticClassifierServiceServer will
// result in compilation errors.
type UnsafeSemanticClassifierServiceServer interface {
	mustEmbedUnimplementedSemanticClassifierServiceServer()
}

func RegisterSemanticClassifierServiceServer(s grpc.ServiceRegistrar, srv SemanticClassifierServiceServer) {
	s.RegisterService(&SemanticClassifierService_ServiceDesc, srv)
}

func _SemanticClassifierService_Classify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticClassifierServiceServer).Classify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticClassifierService_Classify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticClassifierServiceServer).Classify(ctx, req.(*ClassificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticClassifierService_BatchClassify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchClassificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticClassifierServiceServer).BatchClassify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticClassifierService_BatchClassify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticClassifierServiceServer).BatchClassify(ctx, req.(*BatchClassificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticClassifierService_StreamClassify_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SemanticClassifierServiceServer).StreamClassify(&semanticClassifierServiceStreamClassifyServer{stream})
}

type SemanticClassifierService_StreamClassifyServer interface {
	Send(*ClassificationResponse) error
	Recv() (*ClassificationRequest, error)
	grpc.ServerStream
}

type semanticClassifierServiceStreamClassifyServer struct {
	grpc.ServerStream
}

func (x *semanticClassifierServiceStreamClassifyServer) Send(m *ClassificationResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *semanticClassifierServiceStreamClassifyServer) Recv() (*ClassificationRequest, error) {
	m := new(ClassificationRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SemanticClassifierService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticClassifierServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticClassifierService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticClassifierServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SemanticClassifierService_ServiceDesc is the grpc.ServiceDesc for SemanticClassifierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SemanticClassifierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "semantic_router.SemanticClassifierService",
	HandlerType: (*SemanticClassifierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Classify",
			Handler:    _SemanticClassifierService_Classify_Handler,
		},
		{
			MethodName: "BatchClassify",
			Handler:    _SemanticClassifierService_BatchClassify_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _SemanticClassifierService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamClassify",
			Handler:       _SemanticClassifierService_StreamClassify_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "classifier.proto",
}
