// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: classifier.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分类请求消息
type ClassificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                                                                                   // 待分类的文本内容
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                                        // 请求唯一标识符
	CacheEnabled  bool                   `protobuf:"varint,3,opt,name=cache_enabled,json=cacheEnabled,proto3" json:"cache_enabled,omitempty"`                                              // 是否启用缓存
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展元数据
	TimeoutMs     int32                  `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`                                                       // 超时时间（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassificationRequest) Reset() {
	*x = ClassificationRequest{}
	mi := &file_classifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassificationRequest) ProtoMessage() {}

func (x *ClassificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_classifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassificationRequest.ProtoReflect.Descriptor instead.
func (*ClassificationRequest) Descriptor() ([]byte, []int) {
	return file_classifier_proto_rawDescGZIP(), []int{0}
}

func (x *ClassificationRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ClassificationRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ClassificationRequest) GetCacheEnabled() bool {
	if x != nil {
		return x.CacheEnabled
	}
	return false
}

func (x *ClassificationRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ClassificationRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// 分类响应消息
type ClassificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`                                                                         // 预测的类别
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`                                                                   // 置信度
	Scores        map[string]float64     `protobuf:"bytes,3,rep,name=scores,proto3" json:"scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // 所有类别的得分
	LatencyMs     float64                `protobuf:"fixed64,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`                                                    // 推理延迟（毫秒）
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`                                                                             // 推理方法 ("model", "cache", "fallback")
	ModelVersion  string                 `protobuf:"bytes,6,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`                                             // 模型版本
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                      // 响应时间戳
	CacheKey      string                 `protobuf:"bytes,8,opt,name=cache_key,json=cacheKey,proto3" json:"cache_key,omitempty"`                                                         // 缓存键
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassificationResponse) Reset() {
	*x = ClassificationResponse{}
	mi := &file_classifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassificationResponse) ProtoMessage() {}

func (x *ClassificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_classifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassificationResponse.ProtoReflect.Descriptor instead.
func (*ClassificationResponse) Descriptor() ([]byte, []int) {
	return file_classifier_proto_rawDescGZIP(), []int{1}
}

func (x *ClassificationResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ClassificationResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ClassificationResponse) GetScores() map[string]float64 {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *ClassificationResponse) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ClassificationResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ClassificationResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *ClassificationResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ClassificationResponse) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

// 批量分类请求
type BatchClassificationRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Requests      []*ClassificationRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchClassificationRequest) Reset() {
	*x = BatchClassificationRequest{}
	mi := &file_classifier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchClassificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchClassificationRequest) ProtoMessage() {}

func (x *BatchClassificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_classifier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchClassificationRequest.ProtoReflect.Descriptor instead.
func (*BatchClassificationRequest) Descriptor() ([]byte, []int) {
	return file_classifier_proto_rawDescGZIP(), []int{2}
}

func (x *BatchClassificationRequest) GetRequests() []*ClassificationRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

// 批量分类响应
type BatchClassificationResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Responses     []*ClassificationResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchClassificationResponse) Reset() {
	*x = BatchClassificationResponse{}
	mi := &file_classifier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchClassificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchClassificationResponse) ProtoMessage() {}

func (x *BatchClassificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_classifier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchClassificationResponse.ProtoReflect.Descriptor instead.
func (*BatchClassificationResponse) Descriptor() ([]byte, []int) {
	return file_classifier_proto_rawDescGZIP(), []int{3}
}

func (x *BatchClassificationResponse) GetResponses() []*ClassificationResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

// 健康检查请求
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckType     string                 `protobuf:"bytes,1,opt,name=check_type,json=checkType,proto3" json:"check_type,omitempty"` // 检查类型 ("basic", "detailed")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_classifier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_classifier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_classifier_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckRequest) GetCheckType() string {
	if x != nil {
		return x.CheckType
	}
	return ""
}

// 健康检查响应
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                                                         // 服务状态
	Stats         map[string]string      `protobuf:"bytes,2,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 统计信息
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                  // 检查时间戳
	Details       string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`                                                                       // 详细信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_classifier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_classifier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_classifier_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetStats() map[string]string {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *HealthCheckResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HealthCheckResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_classifier_proto protoreflect.FileDescriptor

const file_classifier_proto_rawDesc = "" +
	"\n" +
	"\x10classifier.proto\x12\x0fsemantic_router\"\x9d\x02\n" +
	"\x15ClassificationRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12#\n" +
	"\rcache_enabled\x18\x03 \x01(\bR\fcacheEnabled\x12P\n" +
	"\bmetadata\x18\x04 \x03(\v24.semantic_router.ClassificationRequest.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x05R\ttimeoutMs\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf3\x02\n" +
	"\x16ClassificationResponse\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12K\n" +
	"\x06scores\x18\x03 \x03(\v23.semantic_router.ClassificationResponse.ScoresEntryR\x06scores\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x01R\tlatencyMs\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12#\n" +
	"\rmodel_version\x18\x06 \x01(\tR\fmodelVersion\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tcache_key\x18\b \x01(\tR\bcacheKey\x1a9\n" +
	"\vScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"`\n" +
	"\x1aBatchClassificationRequest\x12B\n" +
	"\brequests\x18\x01 \x03(\v2&.semantic_router.ClassificationRequestR\brequests\"d\n" +
	"\x1bBatchClassificationResponse\x12E\n" +
	"\tresponses\x18\x01 \x03(\v2'.semantic_router.ClassificationResponseR\tresponses\"3\n" +
	"\x12HealthCheckRequest\x12\x1d\n" +
	"\n" +
	"check_type\x18\x01 \x01(\tR\tcheckType\"\xe6\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12E\n" +
	"\x05stats\x18\x02 \x03(\v2/.semantic_router.HealthCheckResponse.StatsEntryR\x05stats\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails\x1a8\n" +
	"\n" +
	"StatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xa5\x03\n" +
	"\x19SemanticClassifierService\x12[\n" +
	"\bClassify\x12&.semantic_router.ClassificationRequest\x1a'.semantic_router.ClassificationResponse\x12j\n" +
	"\rBatchClassify\x12+.semantic_router.BatchClassificationRequest\x1a,.semantic_router.BatchClassificationResponse\x12e\n" +
	"\x0eStreamClassify\x12&.semantic_router.ClassificationRequest\x1a'.semantic_router.ClassificationResponse(\x010\x01\x12X\n" +
	"\vHealthCheck\x12#.semantic_router.HealthCheckRequest\x1a$.semantic_router.HealthCheckResponseBHZFgithub.com/alibaba/higress/plugins/golang-filter/semantic-router/protob\x06proto3"

var (
	file_classifier_proto_rawDescOnce sync.Once
	file_classifier_proto_rawDescData []byte
)

func file_classifier_proto_rawDescGZIP() []byte {
	file_classifier_proto_rawDescOnce.Do(func() {
		file_classifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_classifier_proto_rawDesc), len(file_classifier_proto_rawDesc)))
	})
	return file_classifier_proto_rawDescData
}

var file_classifier_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_classifier_proto_goTypes = []any{
	(*ClassificationRequest)(nil),       // 0: semantic_router.ClassificationRequest
	(*ClassificationResponse)(nil),      // 1: semantic_router.ClassificationResponse
	(*BatchClassificationRequest)(nil),  // 2: semantic_router.BatchClassificationRequest
	(*BatchClassificationResponse)(nil), // 3: semantic_router.BatchClassificationResponse
	(*HealthCheckRequest)(nil),          // 4: semantic_router.HealthCheckRequest
	(*HealthCheckResponse)(nil),         // 5: semantic_router.HealthCheckResponse
	nil,                                 // 6: semantic_router.ClassificationRequest.MetadataEntry
	nil,                                 // 7: semantic_router.ClassificationResponse.ScoresEntry
	nil,                                 // 8: semantic_router.HealthCheckResponse.StatsEntry
}
var file_classifier_proto_depIdxs = []int32{
	6, // 0: semantic_router.ClassificationRequest.metadata:type_name -> semantic_router.ClassificationRequest.MetadataEntry
	7, // 1: semantic_router.ClassificationResponse.scores:type_name -> semantic_router.ClassificationResponse.ScoresEntry
	0, // 2: semantic_router.BatchClassificationRequest.requests:type_name -> semantic_router.ClassificationRequest
	1, // 3: semantic_router.BatchClassificationResponse.responses:type_name -> semantic_router.ClassificationResponse
	8, // 4: semantic_router.HealthCheckResponse.stats:type_name -> semantic_router.HealthCheckResponse.StatsEntry
	0, // 5: semantic_router.SemanticClassifierService.Classify:input_type -> semantic_router.ClassificationRequest
	2, // 6: semantic_router.SemanticClassifierService.BatchClassify:input_type -> semantic_router.BatchClassificationRequest
	0, // 7: semantic_router.SemanticClassifierService.StreamClassify:input_type -> semantic_router.ClassificationRequest
	4, // 8: semantic_router.SemanticClassifierService.HealthCheck:input_type -> semantic_router.HealthCheckRequest
	1, // 9: semantic_router.SemanticClassifierService.Classify:output_type -> semantic_router.ClassificationResponse
	3, // 10: semantic_router.SemanticClassifierService.BatchClassify:output_type -> semantic_router.BatchClassificationResponse
	1, // 11: semantic_router.SemanticClassifierService.StreamClassify:output_type -> semantic_router.ClassificationResponse
	5, // 12: semantic_router.SemanticClassifierService.HealthCheck:output_type -> semantic_router.HealthCheckResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_classifier_proto_init() }
func file_classifier_proto_init() {
	if File_classifier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_classifier_proto_rawDesc), len(file_classifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_classifier_proto_goTypes,
		DependencyIndexes: file_classifier_proto_depIdxs,
		MessageInfos:      file_classifier_proto_msgTypes,
	}.Build()
	File_classifier_proto = out.File
	file_classifier_proto_goTypes = nil
	file_classifier_proto_depIdxs = nil
}
